---
title: "Class06 R functions"
author: "Amy Prichard"
date: "January 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## File reading (again!)

Here we try to use **read.table()** and friends to input some example data into R

Let's insert a code chunk.

```{r}
read.table("https://bioboot.github.io/bggn213_S18/class-material/test1.txt")
  # R can happily read files from the internet - they don't have to be local
  # This one looks gross when read in as-is with read.table()
```

```{r}
file1<-"https://bioboot.github.io/bggn213_S18/class-material/test1.txt"
read.csv(file1)  # read.csv() automatically reads in comma-delimited data
```

```{r}
file2<-"https://bioboot.github.io/bggn213_S18/class-material/test2.txt"
read.table(file2, header = TRUE, sep="$")
```

```{r}
file3<-"https://bioboot.github.io/bggn213_S18/class-material/test3.txt"
read.table(file3)
```



## R functions

(not actually) My first function

```{r}
add <- function(x, y=1) {
  # Sum the input x and y
  x + y
}
```

Let's use the **add()** function

```{r}
add(1)
```

```{r}
add(1,5)
```

```{r}
add(c(1,2,3,4))
```

```{r}
add(c(1,2,3,4),4)
```



```{r}
rescale <- function(x) {
  rng<-range(x)  # range() gives the minimum and maximum values
  (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
x<-c(1,2,NA,3,10)
rescale(x)
```

```{r}
range(x)
```

```{r}
rescale2 <- function(x) {
  rng<-range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
range(x, na.rm=TRUE)
rescale2(x)
```



```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
   if(na.rm) {
     rng <-range(x, na.rm=na.rm)
   } else {
     rng <-range(x)
   }
   print("Hello")
   answer <- (x - rng[1]) / (rng[2] - rng[1])
   print("is it me you are looking for?")
   if(plot) { 
      plot(answer, typ="b", lwd=4) 
   }
   print("I can see it in ...")
   return(answer)
}
```

```{r}
rescale3(1:10, plot=TRUE)
```


## Using the bio3d package

```{r}
library(bio3d)
```

```{r}
pdb <- read.pdb("1HBS")
pdb
```

```{r}
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor") 
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor") 
```


## Question 6: "How would you generalize the original code above to work with any set of input protein structures?"

```{r}

```





