CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Fruit_fly           PRRPNLGREGRPIVLRANHFQVTMPRGYVHHYDINIQPDKCPRKVNREIIETMVHAYSKI
Barrelclover        PLRPGKGSYGRKTLVKANHFFAELPKKDLHQYDVTITPEVTSRGVNRAVMEQLVRLYRDS
Wild_peanut         PLRPGKGSYGTKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEELVRLYRES
Peanut              PLRPGKGSYGTKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEELVRLYRES
Red_clover          PLRPGKGSTGKRCIVKANHFIAELPKKDLHQYDVTITPEVTSRGVNRAVMEQLVRLYRDS
Chickpea            PLRPGKGSCGRKCVVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEQLVRLYRES
Velvet_bean         PLRPGKGSYGTKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEQLVRLYRES
Jequirity_bean      PLRPGKGSYGTRCIVKANHFFAELPNKDLHQYDVTITPEVPSRGVNRAVMEQLVRLYRES
Pigeon_pea          PLRPGKGSYGIKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEQLVKLYRES
Soybean             PLRPGKGSYGTKCVVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEQLVRLYRES
Tepary_bean         PLRPGKGSYGIKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEQLVRLYRES
Mung_bean           PLRPGKGSYGIKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEQLVRLYRES
Peach               PLRPGKGSTGIRCTVKANHFFAELPDKDLHQYDVTITPEVTSRGVNRAVMEQLVKLYRES
Castor_bean         PLRPGKGSTGIRCIVKANHFFAELPDKDLHQYDVTITPEVTSRGVNRAVMEQLVKLYRES
Cork_oak            PLRPGKGSTGTKCMVKANHFFAELPDKDLHQYDVSITPEVTSRGVNRAVMEQLVKLYKET
                    * **. *  *    :.**** . :*   :*:**:.* *:  .* *** ::* :*. * . 

Fruit_fly           -FGVLKPVFDGRNNLYTRDPLPIGNERLELEVTLPGEG------KDRIFRVTIKWQAQVS
Barrelclover        HLGKRLPAYDGRKSLYTAGPLPFISKDFRITLVDEDDG-SGGQRRDREFKVVIKLAARAD
Wild_peanut         HLGKRLPAYDGRKSLYTAGPLPFVSKEFRIMLIDEDDG-TGAQRREREFKVVIKLAARAD
Peanut              HLGKRLPAYDGRKSLYTAGPLPFVSKEFRIMLIDEDDG-TGAQRREREFKVVIKLAARAD
Red_clover          HLGKRLPAYDGRKSLYTAGPLPFISKDFRITLVDEDDG-SGSQRRDREFKVVIKLAARAD
Chickpea            HLGKRLPAYDGRKSLYTAGPLPFISKDFRITLVDDDDG-TGGQRRDREFKVVIKLAARAD
Velvet_bean         HLGKRLPAYDGRKSLYTAGALPFISKEFRITLIDDDEG-AGQQRRDREFKVVIKLAARAD
Jequirity_bean      HLGKRLPAYDGRKSLYTAGPLPFISKEFRITLIDDDEG-AGGQRRDREFKVVIKFAARAD
Pigeon_pea          HLGKRLPAYDGRKSLYTAGPLPFLSKEFRITLVDDDEG-AGGQRRDREFKVVIKLAARAD
Soybean             HLGKRLPAYDGRKSLYTAGPLPFMSKEFRIVLADDDEG-AGGQRRDREFKVVIKLAARAD
Tepary_bean         HLGKRLPAYDGRKSLYTAGPLPFISKEFRITLIDDDEGAAGGQRRDREFKVVIKLAARAD
Mung_bean           HLGKRLPAYDGRKSLYTAGPLPFISKEFRITLIDDDEGAAGGQRRDREFKVVIKLAARAD
Peach               HLGKRLPAYDGRKSLYTAGPLPFLSKEFKIILIDEDDG-PGGQRREREFRVVIKFAARAD
Castor_bean         HLGKRLPAYDGRKSLYTAGPLPFISKEFKITLIDEDDG-SGGQRREREFRVVIKLAARAD
Cork_oak            HLGKRLPAYDGRKSLYTAGPLPFLSKEFKIPLIDEDDG-SGGQRREREFKVVIKLAARAD
                     :*   *.:***:.*** ..**: .: : : :   .:*      .:* *.*.**  *...

Fruit_fly           LFNLEEALEGRTRQIPYDAILALDVVMRHLPSMTYTPVGRSFFSSPEGYYHPLGGGREVW
Barrelclover        LHHLGLFLEGRQTDAPQEALQVLDIVLRELPTSRYCPVGRSFYSPDLGRRQPLGEGLESW
Wild_peanut         LHHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Peanut              LHHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYSPVGRSFYSPDLGRRQPLGEGLESW
Red_clover          LHHLGLFLEGRQTDAPQEALQVLDIVLRELPTSRYCPVGRSFYSPDLGRRQPLGEGLESW
Chickpea            LHHLGLFLEGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Velvet_bean         LHHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Jequirity_bean      LHHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Pigeon_pea          LHHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGDGLESW
Soybean             LHHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Tepary_bean         LHHLGLFLQGKQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Mung_bean           LHHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Peach               LHHLGLFLQGRQADAPQEALQVLDIVLRELPTSRYCPVGRSFYAPDLGRRQSLGEGLESW
Castor_bean         LHHLGLFLQGRQADAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
Cork_oak            LHHLGLFLQGRQADAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESW
                    *.:*   *:*.  : * :*: .**:*:* **:  * ******::.  *  :.** * * *

Fruit_fly           FGFHQSVRPSQWKMMLNIDVSATAFYKAQPVIDFMCEVLDIRDINEQRKPLTDSQRVKFT
Barrelclover        RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLN-RDVSA--RPLSDADRVKIK
Wild_peanut         RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLN-RDVSS--RPLSDADRVKIK
Peanut              RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLN-RDVST--RPLSDADRVKIK
Red_clover          RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLN-RDVSA--RPLSDADRVKIK
Chickpea            RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVTQLLN-RDVST--RPLSDADRVKIK
Velvet_bean         RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVTQLLN-RDVSS--RPLSDSDRVKIK
Jequirity_bean      RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVTQLLN-RDVSS--RPLSDADRVKIK
Pigeon_pea          RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVTQLLN-RDVST--RPLSDADRVKIK
Soybean             RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVNQLLN-RDVSA--RPLSDADRVKIK
Tepary_bean         RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVTQLLN-RDVSA--RPLSDADRVKIK
Mung_bean           RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVTQLLN-RDVSA--RPLSDADRVKIK
Peach               RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLN-RDVTH--RPLSDSDRVKIK
Castor_bean         RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIDFVNQLLN-RDVSS--RPLSDADRVKIK
Cork_oak            RGFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLN-RDVTS--RPLSDADRVKIK
                     **:**:**:*  : ****:*:*** :. ***:*: ::*: **:.   .**:*::***:.

Fruit_fly           KEIKGLKIEITHCGQMRRKYRVCNVTRRPAQMQSFPLQLENGQTVECTVAKYFLDKYRMK
Barrelclover        KALRGIKVEVTHRGNMRRKYRIAGLTSQATRELTFPVD-ERGTMK--SVVEYFFETYGFV
Wild_peanut         KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFSETYGFH
Peanut              KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFSETYGFH
Red_clover          KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFS
Chickpea            KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Velvet_bean         KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Jequirity_bean      KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYDTYGFV
Pigeon_pea          KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Soybean             KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Tepary_bean         KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Mung_bean           KALRGIKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Peach               KALRGVKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Castor_bean         KALRGVKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFV
Cork_oak            KALRGVKVEVTHRGNMRRKYRISGLTSQATRELTFPVD-ERGTMK--SVVEYFYETYGFA
                    * :.*:*:*:** *:******:..:* ..:.  :**:: *.*     :*.:** :.* : 

Fruit_fly           LRYPHLPCLQVGQEHKHTYLPLEVCNIVAGQRCIKKLTDMQTSTMIKATARSAPDREREI
Barrelclover        IQHTQWPCLQVGNPQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPLDRERDI
Wild_peanut         IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Peanut              IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Red_clover          IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPLDRERDI
Chickpea            IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPLDRERDI
Velvet_bean         IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Jequirity_bean      IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Pigeon_pea          IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Soybean             IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Tepary_bean         IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Mung_bean           IQHTQWPCLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDI
Peach               IQHTQWPCLQVGNQQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPHDREQDI
Castor_bean         IQHTQWPCLQVGNQQRPNYLPMEVCKVVEGQRYSKRLNERQITALLKVTCQRPQERERDI
Cork_oak            IQHTQWPCLQVGNQQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPQERERDI
                    :.:.: ******: :. .***:***::* ***  *.*.: * ::::*.*.. . :**.:*

Fruit_fly           NNLVKRADFNNDSYVQEFGLTISNSMMEVRGRVLPPPKLQYGGRVSTGLTGQQLFPPQNK
Barrelclover        MQTVHHNAYHEDPYAKEFGIKISDRLAQVEARILPAPWLKYN---DTGREKDCL------
Wild_peanut         MQTVHHNAYDQDPYAKEFGIKISEKLAQVEARILPPPWLKYH---DTGREKDCL------
Peanut              MQTVHHNAYDQDPYAKEFGIKISEKLAQVEARILPPPWLKYH---DTGREKDCL------
Red_clover          MQTVHHNAYHDDPYAKEFGIKISDKLAQVEARILPPPWLKYH---DTGKEKDCL------
Chickpea            MQTVHHNAYHEDPYAKEFGIKISEKLAQVEARILPAPWLKYH---DTGREKDCL------
Velvet_bean         MQTVHHNAYHDDPYAKEFGIKISEKLAQVEARILPPPWLKYH---DTGREKDCL------
Jequirity_bean      MQTVHHNAYHEDPYAKEFGIKISEKLAQVEARILPAPWLKYH---DTGREKDCL------
Pigeon_pea          MQTVHHNAYHDDPYAKEFGIKISEKLAQVEARILPAPWLKYH---DTGREKDCL------
Soybean             MQTVHHNAYHEDPYAKEFGIKISEKLAQVEARILPAPWLKYH---DTGREKDCL------
Tepary_bean         MQTVYHNAYHEDPYAKEFGIKISEKLAQVEARILPAPWLKYH---DTGREKDCL------
Mung_bean           MQTVYHNAYHEDPYAQEFGIKISEKLAQVEARILPAPWLKYH---DTGREKDCL------
Peach               MRTVRHNAYHEDPYAKEFGIKISENLAQVEARILPPPWLKYH---DTGREKDCL------
Castor_bean         MQTVHHNAYGNDPYAKEFGIKISEKLASVEARILPAPWLKYH---DTGREKDCL------
Cork_oak            MQTVEHNAYHNDPYAKEFGIKISERLASVEARILPAPWLKYH---DTGREKDCL------
                     . * .  : :*.*.:***:.**: : .* .*:**.*.*:*    .**   : *      

Fruit_fly           VSLASPNQGVWDMRGKQFFTGVEIRIWAIACFAPQRTVREDALRNFTQQLQKISNDAGMP
Barrelclover        -----PQVGQWNMMNKKMFNGGSVKYW--LCVNFSRTVQDSVARGFCYELAQMCYVSGME
Wild_peanut         -----PQVGQWNMMNKKMVNGGTVNHW--FCINFSRNVQDSVARTFCYELAQMCQVSGMA
Peanut              -----PQVGQWNMMNKKMVNGGTVNHW--FCINFSRNVQDSVARTFCYELAQMCQVSGMA
Red_clover          -----PQVGQWNMMNKKMVNGGTVNNW--FCVNFSRNVQDSVARGFCSELAHMCYVSGMA
Chickpea            -----PQVGQWNMMNKKMVNGGTVNNW--FCVNFSRNVQDSVARGFCCELAQMCYISGMA
Velvet_bean         -----PQVGQWNMMNKKMVNGGTVNNW--FCINFSRNVQDSVARGFCYELAQMCYISGMA
Jequirity_bean      -----PQVGQWNMMNKKMVNGGTVNNW--FCINFSRNVQDSVARGFCYELAQMCYISGMA
Pigeon_pea          -----PQVGQWNMMNKKMVNGGTVNNW--FCVNFSRNVQDTVARGFCYELAQMCYISGMA
Soybean             -----PQVGQWNMMNKKMVNGGTVNNW--FCINFSRNVQDSVARGFCYELAQMCYISGMA
Tepary_bean         -----PQVGQWNMMNKKMVNGGTVNNW--FCINFSRSVQDSVARGFCYELAQMCYISGMA
Mung_bean           -----PQVGQWNMMNKKMVNGGTVNHW--FCINFSRSVQDSVARGFCYELAQMCYISGMA
Peach               -----PQVGQWNMMNKKMVNGGKVNNW--ICINFSRNVQDSVARGFCSELAQMCYISGMA
Castor_bean         -----PQVGQWNMMNKKMVNGGTVNNW--ICINFSRNVQDSVARGFCYELAQMCYISGMA
Cork_oak            -----PQVGQWNMMNKKMVNGGTVNNW--ICINFSRNVQDSVARGFCYELAQMCYISGMA
                         *: * *:* .*::..*  :. *   *.  .*.*.: . * *  :* ::.  :** 

Fruit_fly           IIGQPCFCKYATGPDQVEPMF--RY----LKIT--FPGLQLVVVVLPGKT-PVYAEVKRV
Barrelclover        FNAEPVVPALTARPDQVEKVLKNRYHDAKSKMP-KDKELDLLIVILPDNNGSLYGDLKRI
Wild_peanut         FNLDPVVPPVSARPDQVEKVLKTRYYDAKNKLP--GKDLDLLIVILPDNNGSLYGDLKRI
Peanut              FNLDPVVPPVSARPDQVEKVLKTRYYDAKNKLP--GKDLDLLIVILPDNNGSLYGDLKRI
Red_clover          FNPEPVVPPLSARPDQVEKVLKTRYHDAKNKLQ--GRELDLLIVILPDNNGSLYGDLKRI
Chickpea            FNPEPVVPPLSARPDQVDKVLKTRYQDAKNKLQ--GRELDLLIVILPDNNGSLYGDLKRI
Velvet_bean         FNPEPVVPPVSSRPDQVEKVLKTRYHDAKSKLQ--GRDLDLLIVILPDNNGSLYGDLKRI
Jequirity_bean      FNPEPVVPPLSARPDQVEKVLKTRYHDAKNKLQ--GRELDLLIVILPDNNGSLYGDLKRI
Pigeon_pea          FNPEPVVPPVSARPDQVEKVLKTRYHDAKNKLQ--GRELDLLIVILPDNNGSLYGDLKRI
Soybean             FTPEPVVPPVSARPDQVEKVLKTRYHDAKNKLQ--GKELDLLIVILPDNNGSLYGDLKRI
Tepary_bean         FNPEPVVPPVSARPDQVEKVLKTRYHDAKNKLQ--GRELDLLIVILPDNNGSLYGDLKRI
Mung_bean           FNPEPVVPPVSARPDQVEKVLKTRYHDAKNKLQ--GRELDLLIVILPDNNGSLYGDLKRI
Peach               FNPEPVLPPISARPDQVEKVLKTRYHDAMTKLRVQGKELDLLVVILPDNNGSLYGDLKRI
Castor_bean         FNPEPVLPPVSARPEQVEKVLKTRYHDAMTKLQ-QGKELDLLIVILPDNNGSLYGELKRI
Cork_oak            FNPEPVLPPLSARPDQVERVLKTRYHDAMTKIQPQGKELDLLIVILPDNNGSLYGDLKRI
                    :  :* .   :: *:**: ::  **     *:      *:*::*:**.:. .:*.::**:

Fruit_fly           GDTVLGMATQCVQAKNVNKTSPQTLSNLCLKINVKLGGINSILVPSIR---PKVFNEPVI
Barrelclover        CETDLGVVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Wild_peanut         CETDLGLVSQCCLTKHVYKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Peanut              CETDLGLVSQCCLTKHVYKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Red_clover          CETDLGVVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLIDALSRRIPLVSDRPTI
Chickpea            CETELGLVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Velvet_bean         CETDLGLVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Jequirity_bean      CETDLGLVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDAISRRIPLVSDRPTI
Pigeon_pea          CETDLGLVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Soybean             CETDLGLVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Tepary_bean         CETDLGLVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVGDRPTI
Mung_bean           CETDLGLVSQCCLTKHVFKMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVGDRPTI
Peach               CETDLGLVSQCCLTKHVFRMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Castor_bean         CETDLGLVSQCCLTKHVFRMNKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
Cork_oak            CETDLGLVSQCCLTKHVFRMSKQYLANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTI
                     :* **:.:**  :*:* . . * *:*:.******:** *::*: ::    * * : *.*

Fruit_fly           FLGADVTHPPAGDNKKPSIAAVVGSMD-AHPSRYAATVRVQQHRQEIIQEL---------
Barrelclover        IFGADVTHPHPGEDSSPSIAAVVASQDWPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Wild_peanut         IFGADVTHPHPGEDSSPSIAAVVASQDWPEITKYAGLVCAQAHRQELIQDLFKQWQDPNR
Peanut              IFGADVTHPHPGEDSSPSIAAVVASQDWPEITKYAGLVCAQAHRQELIQDLFKQWQDPNR
Red_clover          IFGADVTHPHPGEDSSPSIAAVVASQDWPEVTKYAGLVCAQAHRQELIQDLFKQWQDPAR
Chickpea            IFGADVTHPHPGEDMSPSIAAVVASQDWPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Velvet_bean         IFGADVTHPHPGEDSSPSIAAVVASQDYPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Jequirity_bean      IFGADVTHPHPGEDSSPSIAAVVASQDWPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Pigeon_pea          IFGADVTHPHPGEDSSPSIAAVVASQDYPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Soybean             IFGADVTHPHPGEDSSPSIAAVVASQDYPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Tepary_bean         IFGADVTHPHPGEDSSPSIAAVVASQDYPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Mung_bean           IFGADVTHPHPGEDSSPSIAAVVASQDYPEITKYAGLVCAQAHRQELIQDLFKQWQDPVR
Peach               IFGADVTHPHPGEDSSPSIAAVVASQDWPEITKYAGLVCAQAHRQELIQDLFKTWQDPAR
Castor_bean         IFGADVTHPHPGEDSSPSIAAVVASQDWPEVTKYAGLVCAQAHRQELIQDLFKEWQDPVR
Cork_oak            IFGADVTHPHPGEDSSPSIAAVVASQDWPEVTKYAGLVCAQAHRQELIQDLFKTWQDPVR
                    ::******* .*:: .*******.* * .  :.**. * .* ****:**:*         

Fruit_fly           ----SSMVRELLIMFYKSTGGYKPHRIILYRDGVSEGQFPHVLQHELTAIREACIKLEPE
Barrelclover        GTLTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Wild_peanut         GQVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Peanut              GQVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Red_clover          GTLTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Chickpea            GTLTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Velvet_bean         GTVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Jequirity_bean      GTLTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Pigeon_pea          GTVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Soybean             GTVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Tepary_bean         GTVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Mung_bean           GTVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLFELDAIRKACASLEPN
Peach               GTVSGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLYELDAIRKACASLEPN
Castor_bean         GRVTGGMIKELLISFRRATGQ-KPQRIIFYRDGVSEGQFYQVLLYELDAIRKACASLEPN
Cork_oak            GTVSGGMIKELLISFRRATGQ-KPKRIIFYRDGVSEGQFYQVLLYELDAIRKACASLEPN
                        ..*:.**** * .:**  **:***:********** :** .** ***:** .***:

Fruit_fly           YRPGITFIVVQKRHHTRLFCAEKKEQSG--KSGNIPAGTTVDVGITHPTEFDFYLCSHQG
Barrelclover        YQPPVTFVVVQKRHHTRLFASNHQDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Wild_peanut         YQPPVTFVVVQKRHHTRLFASNHHDRNSIDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Peanut              YQPPVTFVVVQKRHHTRLFASNHHDRNSIDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Red_clover          YQPPVTFVVVQKRHHTRLFASNHHDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Chickpea            YQPPVTFVVVQKRHHTRLFASDHRDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Velvet_bean         YQPPVTFVVVQKRHHTRLFASNHHDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Jequirity_bean      YQPPVTFVVVQKRHHTRLFASNHHDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Pigeon_pea          YQPPVTFVVVQKRHHTRLFASNHHDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Soybean             YQPPVTFVVVQKRHHTRLFASNHHDKSSFDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Tepary_bean         YQPPVTFVVVQKRHHTRLFASNHHDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Mung_bean           YQPPVTFVVVQKRHHTRLFASNHHDKSSVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Peach               YQPPVTFVVVQKRHHTRLFANNHHDRNTVDRSGNILPGTVVDSKICHPTEFDFYLCSHAG
Castor_bean         YQPPVTFVVVQKRHHTRLFANNHNDRNAVDKSGNILPGTVVDSKICHPTEFDFYLCSHAG
Cork_oak            YQPPVTFVVVQKRHHTRLFANNHHDRNAVDKSGNILPGTVVDSKICHPTEFDFYLCSHAG
                    *.* :**:***********. ::.:..   .**** .**.**  * ************ *

Fruit_fly           IQGTSRPSHYHVLWDDNHFDSDELQCLTYQLCHTYVRCTRSVSIPAPAYYAHLVAFRARY
Barrelclover        IQGTSRPAHYHVLWDENNFSADGLQSLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Wild_peanut         IQGTSRPAHYHVLWDENNFTADALQMLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Peanut              IQGTSRPAHYHVLWDENNFTADALQMLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Red_clover          IQGTSRPAHYHVLWDENNFTADALQSLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Chickpea            IQGTSRPAHYHVLWDENNFTADALQSLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Velvet_bean         IQGTSRPAHYHVLWDENNFTADGLQTLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Jequirity_bean      IQGTSRPAHYHVLWDENNFTADALQTLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Pigeon_pea          IQGTSRPAHYHVLWDENNFTADALQTLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Soybean             IQGTSRPAHYHVLWDENNFTADALQTLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Tepary_bean         IQGTSRPAHYHVLWDENNFTADALQTLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Mung_bean           IQGTSRPAHYHVLWDENNFTADALQTLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Peach               IQGTSRPAHYHVLWDENKFTADALQSLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Castor_bean         IQGTSRPAHYHVLWDENKFTADGLQSLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
Cork_oak            IQGTSRPAHYHVLWDENKFTADGLQSLTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARF
                    *******:*******:*:* :* ** ** :**:**.******** .*******.*****:

Fruit_fly           HLVEKEHDSGE--------------GSHQSGCSEDRTPGAMA--RAI-TVHADTKKVMYF
Barrelclover        YMEPETSDSGSMTSGAVSRGG----AGAAVG-RSTRAPGANAAVRPLPALKDNVKKVMFY
Wild_peanut         YMEPETSDSGSMTSGAAAGRGM------GAG-RSTRAPGASAAVRPLPSLKDNVKRVMFY
Peanut              YMEPETSDSGSMTSGAAAGRGM------GAG-RSTRAPGASAAVRPLPSLKDNVKRVMFY
Red_clover          YMEPETSDSGSMTSGAVSRGGM----GAAAG-RSTRAPGANAAVRPLPALKENVKRVMFY
Chickpea            YMEPETSDSGSMTSGAVSGRGM----GGGVG-RSTRAPGANAAVRPLPALKENVKRVMFY
Velvet_bean         YMEPETSDSGSMTSGAI-GRGM---GGGGAG-RSTRAPGANAAVRPLPALKENVKRTSSY
Jequirity_bean      YMEPETSDSGSMTSGAVAGRGM---GGGGAG-RSTRAPGASAAVRPLPALKENVKRVMFY
Pigeon_pea          YMEPETSDSGSMTSGAVAGRGM--GGGGGLG-RSTRAPGASAAVRPLPALKENVKRVMFY
Soybean             YMEPETSDSGSMTSGAVAGRGMGGGGGGGVG-RSTRAPGANAAVRPLPALKENVKRVMFY
Tepary_bean         YMEPETSDSGSMTSGAVAGRGM----XGGMG-RSTRAPGANAAVRPLPALKENVKRVMFY
Mung_bean           YMEPETSDSGSMTSGAVAGRGM----GGGIG-RSTRAPGANAAVRPLPALKENVKRVMFY
Peach               YMEPETSDSGSMTSGAP--------GRGGMGARSTRAPGANAAVRPLPALKENVKRVMFY
Castor_bean         YMEPETSDSGSMTSGPVGGRGG---MGGGAGARSTRGPAASAAVRPLPALKENVKRVMFY
Cork_oak            YMEPETSDSGSMTSGAAAGRGM-----GGAGPRSTRPPGANAAVRPLPALKENVKRVMFY
                    ::  :  ***.                   *  . * *.* *  *.: ::: :.*..  :
