CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Wild_peanut      PLRPGKGSYGTKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEELVRLYRES
Peanut           PLRPGKGSYGTKCIVKANHFFAELPNKDLHQYDVTITPEVTSRGVNRAVMEELVRLYRES
                 ************************************************************

Wild_peanut      HLGKRLPAYDGRKSLYTAGPLPFVSKEFRIMLIDEDDGTGAQRREREFKVVIKLAARADL
Peanut           HLGKRLPAYDGRKSLYTAGPLPFVSKEFRIMLIDEDDGTGAQRREREFKVVIKLAARADL
                 ************************************************************

Wild_peanut      HHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYCPVGRSFYSPDLGRRQPLGEGLESWR
Peanut           HHLGLFLQGRQTDAPQEALQVLDIVLRELPTTRYSPVGRSFYSPDLGRRQPLGEGLESWR
                 **********************************.*************************

Wild_peanut      GFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLNRDVSSRPLSDADRVKIKKALR
Peanut           GFYQSIRPTQMGLSLNIDMSSTAFIEPLPVIEFVTQLLNRDVSTRPLSDADRVKIKKALR
                 *******************************************:****************

Wild_peanut      GIKVEVTHRGNMRRKYRISGLTSQATRELTFPVDERGTMKSVVEYFSETYGFHIQHTQWP
Peanut           GIKVEVTHRGNMRRKYRISGLTSQATRELTFPVDERGTMKSVVEYFSETYGFHIQHTQWP
                 ************************************************************

Wild_peanut      CLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDIMQTVHHN
Peanut           CLQVGNTQRPNYLPMEVCKIVEGQRYSKRLNERQITALLKVTCQRPVERERDIMQTVHHN
                 ************************************************************

Wild_peanut      AYDQDPYAKEFGIKISEKLAQVEARILPPPWLKYHDTGREKDCLPQVGQWNMMNKKMVNG
Peanut           AYDQDPYAKEFGIKISEKLAQVEARILPPPWLKYHDTGREKDCLPQVGQWNMMNKKMVNG
                 ************************************************************

Wild_peanut      GTVNHWFCINFSRNVQDSVARTFCYELAQMCQVSGMAFNLDPVVPPVSARPDQVEKVLKT
Peanut           GTVNHWFCINFSRNVQDSVARTFCYELAQMCQVSGMAFNLDPVVPPVSARPDQVEKVLKT
                 ************************************************************

Wild_peanut      RYYDAKNKLPGKDLDLLIVILPDNNGSLYGDLKRICETDLGLVSQCCLTKHVYKMSKQYL
Peanut           RYYDAKNKLPGKDLDLLIVILPDNNGSLYGDLKRICETDLGLVSQCCLTKHVYKMSKQYL
                 ************************************************************

Wild_peanut      ANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTIIFGADVTHPHPGEDSSPSIAAVVAS
Peanut           ANVALKINVKVGGRNTVLVDALSRRIPLVSDRPTIIFGADVTHPHPGEDSSPSIAAVVAS
                 ************************************************************

Wild_peanut      QDWPEITKYAGLVCAQAHRQELIQDLFKQWQDPNRGQVTGGMIKELLISFRRATGQKPQR
Peanut           QDWPEITKYAGLVCAQAHRQELIQDLFKQWQDPNRGQVTGGMIKELLISFRRATGQKPQR
                 ************************************************************

Wild_peanut      IIFYRDGVSEGQFYQVLLFELDAIRKACASLEPNYQPPVTFVVVQKRHHTRLFASNHHDR
Peanut           IIFYRDGVSEGQFYQVLLFELDAIRKACASLEPNYQPPVTFVVVQKRHHTRLFASNHHDR
                 ************************************************************

Wild_peanut      NSIDRSGNILPGTVVDSKICHPTEFDFYLCSHAGIQGTSRPAHYHVLWDENNFTADALQM
Peanut           NSIDRSGNILPGTVVDSKICHPTEFDFYLCSHAGIQGTSRPAHYHVLWDENNFTADALQM
                 ************************************************************

Wild_peanut      LTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARFYMEPETSDSGSMTSGAAAGRGMGAGR
Peanut           LTNNLCYTYARCTRSVSIVPPAYYAHLAAFRARFYMEPETSDSGSMTSGAAAGRGMGAGR
                 ************************************************************

Wild_peanut      STRAPGASAAVRPLPSLKDNVKRVMFY
Peanut           STRAPGASAAVRPLPSLKDNVKRVMFY
                 ***************************
